package com.magneetar.app

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Locks the pairing-code contract between the Android app and the server.
 *
 * The server computes the code as `hashlib.sha256(device_key.encode())
 * .hexdigest()[:8]` (lowercase hex, first 8 chars) — any drift on either
 * side silently breaks the dashboard "Link a device" flow, so these vectors
 * are hardcoded from the server's own algorithm (verified with Python's
 * hashlib) rather than generated by the same code under test.
 */
class PairingCodeTest {

    @Test
    fun `matches the server algorithm for known vectors`() {
        // Verified against `hashlib.sha256(k.encode()).hexdigest()[:8]`.
        assertEquals("1c50ff96", PairingCode.of("devicekey-pair-ok-device"))
        assertEquals("dbf8307f", PairingCode.of("test-device-key"))
    }

    @Test
    fun `is lowercase hex and always 8 chars`() {
        val code = PairingCode.of("some-random-device-key-1234567890")
        assertEquals(8, code.length)
        assertEquals(code, code.lowercase())
        assert(code.all { it in "0123456789abcdef" })
    }

    @Test
    fun `is stable across calls and sensitive to the key`() {
        val key = "mt-1234abcd-key"
        assertEquals(PairingCode.of(key), PairingCode.of(key))
        // Changing any character of the key changes the code (SHA-256 avalanche).
        assert(PairingCode.of(key) != PairingCode.of(key + "x"))
    }

    @Test
    fun `empty key hashes to the SHA-256-of-empty prefix like the server`() {
        // SHA-256 of "" is a real digest (e3b0c442...) — the module must match
        // the server's algorithm exactly for ANY input. HomeActivity only
        // renders the code when the key is non-empty, and the server rejects
        // claims for keyless rows (stored_hash < 8), so this is just the
        // contract staying identical on both sides.
        assertEquals("e3b0c442", PairingCode.of(""))
    }
}
