"""
Magneetar Device-Facing API Routes
All endpoints for device communication (registration, location, media, commands, etc.)
"""

import base64
import hashlib
import json
import re
import sqlite3
from datetime import datetime, timezone
from typing import Optional

from alerts import alert_engine
from auth import (
    check_command_poll_rate_limit,
    check_heartbeat_rate_limit,
    check_location_rate_limit,
    check_media_rate_limit,
    create_device_tokens,
    decode_token,
    get_current_device_or_key,
    get_current_user,
    hash_device_key,
    refresh_access_token,
    security,
    user_id_from_subject,
    verify_api_key,
)
from config import plan_device_limit, settings
from database import get_db, log_audit
from evidence import evidence_builder
from fastapi import APIRouter, Depends, Header, HTTPException
from fastapi.security import HTTPAuthorizationCredentials
from logging_config import get_logger
from models import (
    CommandAck,
    DeviceClaimRequest,
    DeviceRegistration,
    HeartbeatPacket,
    LocationReport,
    MediaReport,
    OfflineQueueUpload,
    RefreshRequest,
    TelemetryPing,
)
from pydantic import BaseModel
from sentinel import sentinel
from websocket_manager import broadcast_to_dashboards, update_device_owner

logger = get_logger("magneetar")

router = APIRouter()

# Device IDs are opaque identifiers generated by the Android app
# ("mt-" + 8 hex chars) but older builds / simulators / tests use other
# strings. Enforcing one exact prefix would brick legitimately-registered
# devices, so we enforce a SAFE CHARSET instead — mirroring the Pydantic
# model (^[A-Za-z0-9_-]+$, 3-64 chars): no whitespace, control chars, dots,
# or quotes. This blocks SQL-injection payloads, log-injection, path
# tricks, and absurd-length junk (the F-06 table-pollution vectors) while
# remaining compatible with every real device. Authentication is the real
# security boundary; format is defense-in-depth.
DEVICE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{2,63}$")


def validate_device_id(device_id: str):
    """Reject malformed device IDs (see DEVICE_ID_RE). Returns None on success;
    raises HTTPException(422) with the offending id otherwise."""
    if not device_id or not DEVICE_ID_RE.match(device_id):
        raise HTTPException(
            status_code=422,
            detail=(
                "Invalid device_id: use 3-64 characters of letters, digits, "
                "dash, underscore, or dot (no spaces or special characters)"
            ),
        )


# ─── Device Registration ─────────────────────────────────────────────────────


def _user_exists(db, user_id: str) -> bool:
    """True when the user account actually exists in the users table."""
    return bool(db.execute("SELECT 1 FROM users WHERE id=?", (user_id,)).fetchone())


def _user_id_from_credentials(
    credentials: Optional[HTTPAuthorizationCredentials],
) -> Optional[str]:
    """Resolve a user id from an optional bearer token, if it is a user token.

    Returns None when the header is absent, unparseable, or not a user token
    (e.g. a device token). Callers treat None as "no account linking".
    """
    if not credentials or not credentials.credentials:
        return None
    try:
        payload = decode_token(credentials.credentials)
    except HTTPException:
        return None
    return user_id_from_subject(payload.get("sub", ""))


@router.post("/api/device/register")
async def register_device(
    reg: DeviceRegistration,
    db: sqlite3.Connection = Depends(get_db),
    x_api_key: str = Depends(verify_api_key),
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
):
    """Register a new device and get JWT tokens. Requires API key.

    If a valid user bearer token is also supplied, the device is linked to
    that account (owner_id is set) so it appears in the user's dashboard.
    """
    validate_device_id(reg.device_id)
    now = datetime.now(timezone.utc).isoformat()
    device_key_hash = None
    if reg.device_key:
        device_key_hash = hash_device_key(reg.device_key)

    owner_id = _user_id_from_credentials(credentials)

    # A stale user token (e.g. the account was permanently deleted) must not
    # re-link a device to a ghost owner — verify the account still exists.
    if owner_id and not _user_exists(db, owner_id):
        owner_id = None

    existing = db.execute("SELECT id, owner_id FROM devices WHERE id=?", (reg.device_id,)).fetchone()

    # Enforce the per-user device limit when this registration links the device
    # to an account (new links only — re-registering an already-owned device is fine).
    if owner_id:
        already_owned = existing["owner_id"] if existing else None
        if already_owned and already_owned != owner_id:
            # Orphaned ownership (owner account was permanently deleted) is
            # claimable — only block when the existing owner account is real.
            if _user_exists(db, already_owned):
                raise HTTPException(status_code=403, detail="Device already linked to another account")
        if already_owned is None or not _user_exists(db, already_owned):
            _enforce_device_limit(db, owner_id)

    if existing:
        db.execute(
            """UPDATE devices
               SET device_fingerprint=?, model=?, os_version=?,
                   app_version=?, imei_hash=?, sim_serial_hash=?,
                   device_key_hash=COALESCE(?, device_key_hash),
                   owner_id=COALESCE(?, owner_id), last_seen=?
               WHERE id=?""",
            (
                reg.fingerprint,
                reg.model,
                reg.os_version,
                reg.app_version,
                reg.imei_hash,
                reg.sim_serial_hash,
                device_key_hash,
                owner_id,
                now,
                reg.device_id,
            ),
        )
    else:
        db.execute(
            """INSERT INTO devices (id, device_fingerprint, model, os_version,
               app_version, imei_hash, sim_serial_hash, device_key_hash, owner_id, last_seen, registered)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                reg.device_id,
                reg.fingerprint,
                reg.model,
                reg.os_version,
                reg.app_version,
                reg.imei_hash,
                reg.sim_serial_hash,
                device_key_hash,
                owner_id,
                now,
                now,
            ),
        )

    db.commit()

    # Sync the WebSocket owner cache with the ACTUAL owner after the write.
    # COALESCE keeps an existing owner on re-register, so re-read the row to
    # avoid flipping the cache to the registering user when ownership didn't
    # change (which would leak another user's broadcasts to the wrong client).
    final_owner = db.execute("SELECT owner_id FROM devices WHERE id=?", (reg.device_id,)).fetchone()
    update_device_owner(reg.device_id, final_owner["owner_id"] if final_owner else None)

    tokens = create_device_tokens(reg.device_id)
    log_audit("device_registered", actor=reg.device_id, details=reg.model)

    return {
        **tokens,
        "has_device_key": device_key_hash is not None,
        "owner_id": final_owner["owner_id"] if final_owner else None,
        "server_time": now,
    }


def _enforce_device_limit(db, user_id: str):
    """Raise 403 when the user already owns their plan's device allowance.

    The allowance comes from the account's tier (free=1, personal=3,
    guardian=10, enterprise/admin=unlimited) — see plan_device_limit().
    """
    tier_row = db.execute("SELECT tier FROM users WHERE id=?", (user_id,)).fetchone()
    tier = tier_row["tier"] if tier_row else "free"
    limit = plan_device_limit(tier)
    count = db.execute("SELECT COUNT(*) as cnt FROM devices WHERE owner_id=?", (user_id,)).fetchone()["cnt"]
    if count >= limit:
        raise HTTPException(
            status_code=403,
            detail=f"Device limit reached ({count}/{limit}) — upgrade your plan to protect more devices",
        )


@router.post("/api/device/claim")
async def claim_device(
    req: DeviceClaimRequest,
    db: sqlite3.Connection = Depends(get_db),
    user_id: str = Depends(get_current_user),
    x_device_key: Optional[str] = Header(None),
):
    """Link an existing device to the authenticated user's account.

    The device is identified by its per-device secret key (x-device-key header)
    or, failing that, by an explicit device_id in the body. The user is
    authenticated with a user bearer token. Once linked, the device shows up
    in the user's dashboard and is scoped to their account.
    """
    if user_id == "api_key_user":
        raise HTTPException(status_code=401, detail="User authentication required")

    # A stale token from a permanently deleted account must not claim devices
    # (that would re-create a ghost link — same bug class as register).
    if not _user_exists(db, user_id):
        raise HTTPException(status_code=401, detail="Account no longer exists")

    device = None
    if x_device_key:
        key_hash = hash_device_key(x_device_key)
        device = db.execute("SELECT id, owner_id FROM devices WHERE device_key_hash=?", (key_hash,)).fetchone()
    if device is None and req.device_id:
        device = db.execute("SELECT id, owner_id FROM devices WHERE id=?", (req.device_id,)).fetchone()
    if device is None:
        raise HTTPException(status_code=404, detail="Device not found")

    existing_owner = device["owner_id"]
    # Only block cross-account claims when the existing owner is a REAL account.
    # A device whose owner account was permanently deleted (orphaned ownership,
    # e.g. after a DB restore) is claimable by anyone with the device key/id.
    if existing_owner and _user_exists(db, existing_owner) and existing_owner != user_id:
        raise HTTPException(status_code=403, detail="Device already linked to another account")

    # Enforce per-user device limit before linking — skip when the device is
    # already owned by this user so re-claims stay idempotent (same as the
    # register path, which skips the limit for same-owner re-registrations).
    if existing_owner != user_id:
        _enforce_device_limit(db, user_id)

    db.execute("UPDATE devices SET owner_id=? WHERE id=?", (user_id, device["id"]))
    db.commit()
    update_device_owner(device["id"], user_id)
    log_audit("device_claimed", actor=user_id, details=f"Device: {device['id']}")

    return {"status": "ok", "device_id": device["id"], "owner_id": user_id}


# ─── Location Reports ────────────────────────────────────────────────────────


@router.post("/api/device/location")
async def post_location(
    report: TelemetryPing,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Receive telemetry ping from device."""
    if report.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_location_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")

    is_valid, reason = sentinel.validate_report(report, None)
    if not is_valid:
        log_audit("invalid_location_report", actor=device_id, details=reason)

    now = datetime.now(timezone.utc).isoformat()
    ts = report.device_timestamp or now

    history = db.execute(
        "SELECT * FROM locations WHERE device_id=? ORDER BY server_timestamp DESC LIMIT 10",
        (device_id,),
    ).fetchall()

    history_dicts = [dict(h) for h in history]
    score, threat_level, anomalies = sentinel.compute_score(report, history_dicts)

    db.execute(
        """INSERT INTO locations (device_id, lat, lng, altitude, accuracy_horizontal,
           accuracy_vertical, confidence_level, speed, bearing, activity_type,
           step_count, provider, gps_satellite_count, wifi_bssids, cell_tower_ids,
           ble_devices_nearby, battery_percent, is_charging, network_type,
           signal_strength_dbm, is_location_enabled, is_airplane_mode,
           sim_changed, sim_serial_hash, sentinel_score, threat_level, anomalies,
           device_timestamp, server_timestamp, was_queued, queued_at,
           queue_position, ping_sequence)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            device_id,
            report.lat,
            report.lng,
            report.altitude,
            report.accuracy_horizontal,
            report.accuracy_vertical,
            report.confidence_level,
            report.speed,
            report.bearing,
            report.activity_type,
            report.step_count,
            report.provider,
            report.gps_satellite_count,
            json.dumps(report.wifi_bssids or []),
            json.dumps(report.cell_tower_ids or []),
            report.ble_devices_nearby,
            report.battery_percent,
            report.is_charging,
            report.network_type,
            report.signal_strength_dbm,
            report.is_location_enabled,
            report.is_airplane_mode,
            report.sim_changed,
            report.sim_serial_hash,
            score,
            threat_level,
            json.dumps(anomalies or []),
            ts,
            now,
            report.was_queued,
            report.queued_at,
            report.queue_position,
            report.ping_sequence,
        ),
    )

    # COALESCE: an old app build that doesn't send capture_armed (None) must
    # not wipe the stored state — the column keeps its last known value.
    db.execute(
        "UPDATE devices SET last_seen=?, sentinel_score=?, capture_armed=COALESCE(?, capture_armed) WHERE id=?",
        (now, score, report.capture_armed, device_id),
    )
    db.commit()

    if score >= settings.THEFT_SCORE_THRESHOLD:
        sentinel.auto_activate_theft_mode(device_id, score)
        await alert_engine.send_all(
            device_id,
            "theft_detected",
            {"location": f"{report.lat},{report.lng}", "time": now, "score": score},
        )

    geofences = db.execute("SELECT * FROM geofences WHERE device_id=? AND active=1", (device_id,)).fetchall()

    if geofences:
        triggered = sentinel.check_geofences(report, [dict(g) for g in geofences])
        for event in triggered:
            if event["event"] == "exited" and not event["is_safe_zone"]:
                await alert_engine.send_all(
                    device_id,
                    "geofence_exit",
                    {
                        "zone_name": event["name"],
                        "location": f"{report.lat},{report.lng}",
                        "time": now,
                    },
                )

    await broadcast_to_dashboards(
        {
            "type": "location",
            "data": {
                "device_id": device_id,
                "lat": report.lat,
                "lng": report.lng,
                "speed": report.speed,
                "battery": report.battery_percent,
                "sentinel_score": score,
                "threat_level": threat_level,
                "timestamp": now,
            },
        }
    )

    commands = db.execute(
        "SELECT id, command, params, priority FROM commands WHERE device_id=? AND status='pending' ORDER BY priority",
        (device_id,),
    ).fetchall()

    return {
        "status": "ok",
        "commands_pending": len(commands),
        "server_time": now,
    }


@router.post("/api/device/location/simple")
async def post_location_simple(
    report: LocationReport,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Simplified location report for basic tracking."""
    now = datetime.now(timezone.utc).isoformat()
    ts = report.timestamp or now

    db.execute(
        (
            "INSERT INTO locations (device_id, lat, lng, accuracy, provider, "
            "device_timestamp, server_timestamp) VALUES (?,?,?,?,?,?,?)"
        ),
        (device_id, report.lat, report.lng, report.accuracy, report.provider, ts, now),
    )
    db.execute("UPDATE devices SET last_seen=? WHERE id=?", (now, device_id))
    db.commit()

    return {"status": "ok", "server_time": now}


# ─── Media Uploads ───────────────────────────────────────────────────────────


@router.post("/api/device/media")
async def post_media(
    report: MediaReport,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Upload media (photo/audio) from device."""
    if report.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_media_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Media upload rate limit exceeded")

    now = datetime.now(timezone.utc).isoformat()
    ts = report.timestamp or now

    data = base64.b64decode(report.data_b64)
    sha256_hash = hashlib.sha256(data).hexdigest()

    case = db.execute(
        "SELECT id FROM evidence_cases WHERE device_id=? AND status='active' ORDER BY created_at DESC LIMIT 1",
        (device_id,),
    ).fetchone()

    case_id = case["id"] if case else None

    db.execute(
        """INSERT INTO media (device_id, type, data_b64, lat, lng, timestamp,
           evidence_case_id, sha256_hash)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            device_id,
            report.type,
            report.data_b64,
            report.lat,
            report.lng,
            ts,
            case_id,
            sha256_hash,
        ),
    )
    db.commit()

    media_id = db.execute("SELECT last_insert_rowid()").fetchone()[0]

    if case_id:
        evidence_builder.add_media_to_case(case_id, report.type, report.data_b64)

    await broadcast_to_dashboards(
        {
            "type": "media",
            "data": {
                "device_id": device_id,
                "media_id": media_id,
                "type": report.type,
                "timestamp": ts,
            },
        }
    )

    return {
        "status": "ok",
        "media_id": media_id,
        "evidence_case_id": case_id,
    }


# ─── Commands (Device Polling) ───────────────────────────────────────────────


@router.get("/api/device/commands/{device_id}")
async def get_device_commands(
    device_id: str,
    db: sqlite3.Connection = Depends(get_db),
    token_device_id: str = Depends(get_current_device_or_key),
):
    """Poll for pending commands."""
    if device_id != token_device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_command_poll_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Command poll rate limit exceeded")

    rows = db.execute(
        """SELECT id, command, params, priority
           FROM commands
           WHERE device_id=? AND status='pending'
           AND (expires_at IS NULL OR datetime(expires_at) > datetime('now'))
           ORDER BY priority ASC""",
        (device_id,),
    ).fetchall()

    return {"commands": [dict(r) for r in rows]}


@router.post("/api/device/commands/{command_id}/ack")
async def ack_command(
    command_id: int,
    ack: CommandAck,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Acknowledge command execution."""
    now = datetime.now(timezone.utc).isoformat()

    db.execute(
        "UPDATE commands SET status=?, executed_at=? WHERE id=? AND device_id=?",
        (ack.status, now, command_id, device_id),
    )
    db.commit()

    await broadcast_to_dashboards(
        {
            "type": "command_ack",
            "data": {
                "command_id": command_id,
                "device_id": device_id,
                "status": ack.status,
            },
        }
    )

    return {"status": "ok"}


# ─── Heartbeat ───────────────────────────────────────────────────────────────


@router.post("/api/device/heartbeat")
async def post_heartbeat(
    hb: HeartbeatPacket,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Receive heartbeat from device."""
    if hb.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_heartbeat_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Heartbeat rate limit exceeded")

    now = datetime.now(timezone.utc).isoformat()

    db.execute(
        """INSERT INTO heartbeats (device_id, timestamp, battery_percent, is_charging,
           network_type, device_admin_active, sim_hash, app_version, pending_evidence_count)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            device_id,
            now,
            hb.battery_percent,
            hb.is_charging,
            hb.network_type,
            hb.device_admin_active,
            hb.sim_hash,
            hb.app_version,
            hb.pending_evidence_count,
        ),
    )

    # COALESCE keeps the last known armed state when an old app build omits
    # the field (None) — a fresh report never wipes it to NULL.
    db.execute(
        "UPDATE devices SET last_seen=?, app_version=?, capture_armed=COALESCE(?, capture_armed) WHERE id=?",
        (now, hb.app_version, hb.capture_armed, device_id),
    )

    # ── Commit BEFORE any nested writes ──────────────────────────────────────
    # auto_activate_theft_mode() and log_audit() open their OWN sqlite
    # connection. Calling them while this request's write transaction is still
    # open makes the nested writer block on our uncommitted writes and raise
    # "database is locked" after busy_timeout — the resulting 500 rolls back
    # the heartbeat's last_seen update, so the dashboard freezes the device's
    # "last seen" at its previous time even though the phone is alive.
    db.commit()

    # Device admin being disabled is a strong theft signal (weight 40 in
    # sentinel.THEFT_SIGNALS), but it must NOT auto-activate stolen mode from a
    # bare heartbeat: escalation is reserved for the location path's
    # confirmation-gated score (>= THEFT_SCORE_THRESHOLD). Persist the elevated
    # score so the dashboard reflects the signal; the location path still owns
    # escalation to stolen.
    if hb.device_admin_active is False:
        db.execute(
            "UPDATE devices SET sentinel_score = MAX(sentinel_score, 40) WHERE id=?",
            (device_id,),
        )
        db.commit()

    device = db.execute("SELECT operating_mode FROM devices WHERE id=?", (device_id,)).fetchone()

    return {
        "status": "ok",
        "operating_mode": device["operating_mode"] if device else "normal",
        "server_time": now,
    }


# ─── Token Refresh ───────────────────────────────────────────────────────────


@router.post("/api/device/refresh")
async def refresh_token(req: RefreshRequest):
    """Refresh JWT tokens."""
    return refresh_access_token(req.refresh_token)


# ─── Offline Queue ───────────────────────────────────────────────────────────


@router.post("/api/device/offline-queue")
async def upload_offline_queue(
    queue: OfflineQueueUpload,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Batch upload of queued telemetry pings."""
    processed = 0
    last_armed = None

    for ping in queue.pings:
        if ping.device_id != device_id:
            continue

        now = datetime.now(timezone.utc).isoformat()
        ts = ping.device_timestamp or now

        history = db.execute(
            "SELECT * FROM locations WHERE device_id=? ORDER BY server_timestamp DESC LIMIT 10",
            (device_id,),
        ).fetchall()
        history_dicts = [dict(h) for h in history]
        score, threat_level, anomalies = sentinel.compute_score(ping, history_dicts)

        db.execute(
            """INSERT INTO locations (device_id, lat, lng, altitude, accuracy_horizontal,
               confidence_level, speed, bearing, activity_type, provider,
               battery_percent, is_charging, network_type, sentinel_score,
               threat_level, anomalies, device_timestamp, server_timestamp, was_queued,
               queued_at, queue_position, ping_sequence)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                device_id,
                ping.lat,
                ping.lng,
                ping.altitude,
                ping.accuracy_horizontal,
                ping.confidence_level,
                ping.speed,
                ping.bearing,
                ping.activity_type,
                ping.provider,
                ping.battery_percent,
                ping.is_charging,
                ping.network_type,
                score,
                threat_level,
                json.dumps(anomalies or []),
                ts,
                now,
                True,
                ping.queued_at,
                ping.queue_position,
                ping.ping_sequence,
            ),
        )
        last_armed = ping.capture_armed
        processed += 1

    # Same COALESCE keep-last-state semantics as the live telemetry path: a
    # queued ping's capture_armed is persisted when present, and a None (old
    # build) never wipes a previously reported state.
    db.execute(
        "UPDATE devices SET last_seen=?, capture_armed=COALESCE(?, capture_armed) WHERE id=?",
        (datetime.now(timezone.utc).isoformat(), last_armed, device_id),
    )
    db.commit()

    return {"status": "ok", "processed": processed}


# ─── FCM Token Registration ─────────────────────────────────────────────────


class FCMTokenRequest(BaseModel):
    fcm_token: str
    device_id: str = ""
    platform: Optional[str] = "android"


@router.post("/api/device/fcm-token")
async def register_fcm_token(
    req: FCMTokenRequest,
    db: sqlite3.Connection = Depends(get_db),
    resolved_device_id: str = Depends(get_current_device_or_key),
):
    """Register an FCM push notification token for a device.

    Security (F-06): this endpoint must never create device rows. The old
    code inserted a placeholder device (fingerprint='fcm_*') for ANY
    device_id, so anyone could pollute the devices table — and the shared
    API key (public, embedded in every APK) let anyone do it with an
    arbitrary id. The device must ALREADY be registered: real devices
    authenticate with their per-device key/JWT (resolved_device_id is then
    their real id), and the fcm_tokens.device_id FK enforces existence.
    """
    now = datetime.now(timezone.utc).isoformat()

    device_id = resolved_device_id

    # The shared API key (embedded in every APK — public) has NO principal, so
    # it must not be able to attach a push token to an arbitrary device:
    # with the old fallback, anyone with the key could register their own FCM
    # token under a victim's EXISTING device_id and receive the victim's theft
    # alerts (push hijacking). The only non-device id still accepted is the
    # fixed 'broadcast' relay constant, which the alert engine uses to fan out
    # to tokens registered without a device (kept for backward compat).
    if device_id == "api_key_user" or not device_id:
        requested = req.device_id.strip() if req.device_id else ""
        if requested != "broadcast":
            raise HTTPException(status_code=401, detail="Device authorization required")
        device_id = "broadcast"

    # A device that isn't registered yet must reject the token registration
    # (the app registers the device before sending its FCM token). The
    # legacy 'broadcast' relay is the one allowed non-device id — it is a
    # fixed constant, not attacker-controlled.
    if device_id != "broadcast":
        existing = db.execute("SELECT id FROM devices WHERE id=?", (device_id,)).fetchone()
        if not existing:
            raise HTTPException(status_code=401, detail="Device not registered")

    db.execute(
        """INSERT INTO fcm_tokens (device_id, fcm_token, platform, updated_at)
           VALUES (?, ?, ?, ?)
           ON CONFLICT(device_id, fcm_token) DO UPDATE SET updated_at=?""",
        (device_id, req.fcm_token, req.platform, now, now),
    )
    db.commit()

    logger.info(
        "FCM token registered",
        extra={"extra_data": {"device_id": device_id, "platform": req.platform}},
    )

    return {"status": "ok", "message": "FCM token registered", "device_id": device_id}
