"""
Magneetar Device-Facing API Routes
All endpoints for device communication (registration, location, media, commands, etc.)
"""

import base64
import hashlib
import json
import re
import sqlite3
from datetime import datetime, timedelta, timezone
from functools import partial
from typing import Optional

from alerts import alert_engine
from archive_monitor import unarchive_device
from auth import (
    check_command_poll_rate_limit,
    check_heartbeat_rate_limit,
    check_location_rate_limit,
    check_media_rate_limit,
    create_device_tokens,
    decode_token,
    get_current_device_or_key,
    get_current_user,
    hash_device_key,
    refresh_access_token,
    security,
    user_id_from_subject,
    verify_api_key,
)
from config import plan_device_limit, settings
from database import get_db, log_audit
from encryption import decrypt_location_row, encrypt_location_for_store
from evidence import evidence_builder
from fastapi import APIRouter, Depends, Header, HTTPException
from fastapi.security import HTTPAuthorizationCredentials
from location_validator import validate_location_report
from logging_config import get_logger
from models import (
    CommandAck,
    DeviceClaimRequest,
    DeviceRegistration,
    HeartbeatPacket,
    LocationReport,
    MediaReport,
    OfflineQueueUpload,
    RefreshRequest,
    TelemetryPing,
)
from pydantic import BaseModel
from sentinel import sentinel
from websocket_manager import broadcast_to_dashboards, update_device_owner
from write_queue import enqueue_write, write_queue_enabled

logger = get_logger("magneetar")

router = APIRouter()

# Device IDs are opaque identifiers generated by the Android app
# ("mt-" + 8 hex chars) but older builds / simulators / tests use other
# strings. Enforcing one exact prefix would brick legitimately-registered
# devices, so we enforce a SAFE CHARSET instead — mirroring the Pydantic
# model (^[A-Za-z0-9_-]+$, 3-64 chars): no whitespace, control chars, dots,
# or quotes. This blocks SQL-injection payloads, log-injection, path
# tricks, and absurd-length junk (the F-06 table-pollution vectors) while
# remaining compatible with every real device. Authentication is the real
# security boundary; format is defense-in-depth.
DEVICE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{2,63}$")


def validate_device_id(device_id: str):
    """Reject malformed device IDs (see DEVICE_ID_RE). Returns None on success;
    raises HTTPException(422) with the offending id otherwise."""
    if not device_id or not DEVICE_ID_RE.match(device_id):
        raise HTTPException(
            status_code=422,
            detail=(
                "Invalid device_id: use 3-64 characters of letters, digits, "
                "dash, underscore, or dot (no spaces or special characters)"
            ),
        )


# ─── Device Registration ─────────────────────────────────────────────────────


def _user_exists(db, user_id: str) -> bool:
    """True when the user account actually exists in the users table."""
    return bool(db.execute("SELECT 1 FROM users WHERE id=?", (user_id,)).fetchone())


def _user_id_from_credentials(
    credentials: Optional[HTTPAuthorizationCredentials],
) -> Optional[str]:
    """Resolve a user id from an optional bearer token, if it is a user token.

    Returns None when the header is absent, unparseable, or not a user token
    (e.g. a device token). Callers treat None as "no account linking".
    """
    if not credentials or not credentials.credentials:
        return None
    try:
        payload = decode_token(credentials.credentials)
    except HTTPException:
        return None
    return user_id_from_subject(payload.get("sub", ""))


@router.post("/api/device/register")
async def register_device(
    reg: DeviceRegistration,
    db: sqlite3.Connection = Depends(get_db),
    x_api_key: str = Depends(verify_api_key),
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
):
    """Register a new device and get JWT tokens. Requires API key.

    If a valid user bearer token is also supplied, the device is linked to
    that account (owner_id is set) so it appears in the user's dashboard.
    """
    validate_device_id(reg.device_id)
    now = datetime.now(timezone.utc).isoformat()
    device_key_hash = None
    if reg.device_key:
        device_key_hash = hash_device_key(reg.device_key)

    owner_id = _user_id_from_credentials(credentials)

    # A stale user token (e.g. the account was permanently deleted) must not
    # re-link a device to a ghost owner — verify the account still exists.
    if owner_id and not _user_exists(db, owner_id):
        owner_id = None

    existing = db.execute(
        "SELECT id, owner_id FROM devices WHERE id=?", (reg.device_id,)
    ).fetchone()  # ── Fingerprint dedup (reinstall recovery) ────────────────────────────
    # A reinstall wipes the app's SharedPreferences, so the new install
    # generates a FRESH device_id even though it is the SAME physical phone
    # (its ANDROID_ID fingerprint is stable across reinstalls). Without this
    # step, every reinstall leaves a stale duplicate row behind. When the
    # requested id is new but a device with the same fingerprint already
    # exists and is unowned (or its owner account is gone), we adopt the
    # existing row as canonical instead of creating a duplicate — the
    # register response returns the canonical id and the app persists it.
    #
    # Staleness guard: adoption of an UNOWNED/orphaned row ONLY happens when
    # the existing row's last report is older than MT_DEVICE_ADOPT_AFTER_HOURS
    # (default 24h; a reinstall goes silent the moment the old app is
    # removed). A CONCURRENTLY-registered device that shares a fingerprint
    # must never be hijacked — emulators, test fixtures, and dual-app
    # scenarios can legitimately share a fingerprint, and those rows report
    # recently.
    #
    # SAME-OWNER exception: a row the REGISTERING USER already owns (they
    # reinstalled the app on their own phone and are linking with their
    # token) is adopted REGARDLESS of staleness — it is provably their own
    # device (owner_id matches their token), so no theft vector exists and
    # the per-user device limit is not re-charged for a reinstall.
    #
    # Security: adoption is only for UNOWNED/orphaned rows OR rows owned by
    # the SAME authenticated user. A row owned by a DIFFERENT real account is
    # never re-pointed by an anonymous reinstall (that would let a thief who
    # reinstalled the app claim the victim's device by guessing the
    # fingerprint) — those duplicates are resolved by the owner via the
    # dashboard's password-gated delete.
    canonical_id = reg.device_id
    if existing is None and reg.fingerprint:
        candidates = db.execute(
            """SELECT id, owner_id FROM devices
               WHERE device_fingerprint=? AND id != ?
               ORDER BY datetime(COALESCE(last_seen, registered)) DESC""",
            (reg.fingerprint, reg.device_id),
        ).fetchall()
        for canonical in candidates:
            canonical_owner = canonical["owner_id"]
            if owner_id and canonical_owner == owner_id:
                # Same user reinstalling their own device — adopt regardless
                # of staleness; the token already proves ownership.
                existing = canonical
                canonical_id = canonical["id"]
                break
            if canonical_owner is None or not _user_exists(db, canonical_owner):
                # Unowned/orphaned — require the silence window so a
                # concurrently-reporting device is never hijacked.
                stale = db.execute(
                    """SELECT (last_seen IS NULL OR
                               datetime(last_seen) < datetime('now', ?)) AS is_stale
                       FROM devices WHERE id=?""",
                    (f"-{settings.DEVICE_ADOPT_AFTER_HOURS} hours", canonical["id"]),
                ).fetchone()
                if stale and stale["is_stale"]:
                    existing = canonical
                    canonical_id = canonical["id"]
                    break

    # Enforce the per-user device limit when this registration links the device
    # to an account (new links only — re-registering an already-owned device is fine).
    if owner_id:
        already_owned = existing["owner_id"] if existing else None
        if already_owned and already_owned != owner_id:
            # Orphaned ownership (owner account was permanently deleted) is
            # claimable — only block when the existing owner account is real.
            if _user_exists(db, already_owned):
                raise HTTPException(status_code=403, detail="Device already linked to another account")
        if already_owned is None or not _user_exists(db, already_owned):
            _enforce_device_limit(db, owner_id)

    if existing:
        # On the ADOPTION path (fresh reinstall re-pointed at the pre-existing
        # row) the app generated a brand-new device_key, so the key hash MUST
        # be replaced — keeping the old one would lock the reinstalled app out
        # of its own device. On a plain re-register of the same id, COALESCE
        # keeps an existing key when the payload omits one.
        if canonical_id != reg.device_id and device_key_hash is not None:
            db.execute(
                """UPDATE devices
                   SET device_fingerprint=?, model=?, os_version=?,
                       app_version=?, imei_hash=?, sim_serial_hash=?,
                       device_key_hash=?, owner_id=COALESCE(?, owner_id), last_seen=?
                   WHERE id=?""",
                (
                    reg.fingerprint,
                    reg.model,
                    reg.os_version,
                    reg.app_version,
                    reg.imei_hash,
                    reg.sim_serial_hash,
                    device_key_hash,
                    owner_id,
                    now,
                    canonical_id,
                ),
            )
        else:
            db.execute(
                """UPDATE devices
                   SET device_fingerprint=?, model=?, os_version=?,
                       app_version=?, imei_hash=?, sim_serial_hash=?,
                       device_key_hash=COALESCE(?, device_key_hash),
                       owner_id=COALESCE(?, owner_id), last_seen=?
                   WHERE id=?""",
                (
                    reg.fingerprint,
                    reg.model,
                    reg.os_version,
                    reg.app_version,
                    reg.imei_hash,
                    reg.sim_serial_hash,
                    device_key_hash,
                    owner_id,
                    now,
                    canonical_id,
                ),
            )
    else:
        # Unowned-registration cap (F-07): the low-privilege DEVICE key is
        # PUBLIC (it ships inside every APK), so a new unowned device row
        # costs nothing to create — cap how many can exist so an attacker
        # can't flood the devices table with junk. Account-linked
        # registrations are bounded by the per-user device limit instead.
        # Adoption of an existing unowned row never hits this (no new row is
        # created).
        if owner_id is None:
            unowned = db.execute("SELECT COUNT(*) as cnt FROM devices WHERE owner_id IS NULL").fetchone()["cnt"]
            if unowned >= settings.MAX_UNOWNED_DEVICES:
                raise HTTPException(
                    status_code=403,
                    detail=(
                        "Too many unowned devices on this server — register the "
                        "device to your account instead (sign in on the phone first)"
                    ),
                )

        db.execute(
            """INSERT INTO devices (id, device_fingerprint, model, os_version,
               app_version, imei_hash, sim_serial_hash, device_key_hash, owner_id, last_seen, registered)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                canonical_id,
                reg.fingerprint,
                reg.model,
                reg.os_version,
                reg.app_version,
                reg.imei_hash,
                reg.sim_serial_hash,
                device_key_hash,
                owner_id,
                now,
                now,
            ),
        )

    # Prefill the Offline Command Relay recipient (sms_phone) from the SIM
    # number the app reports — but ONLY when sms_phone is still NULL, so an
    # owner-confirmed number is never overwritten by a later registration.
    if reg.sim_phone:
        db.execute(
            "UPDATE devices SET sms_phone=COALESCE(sms_phone, ?) WHERE id=?",
            (reg.sim_phone, canonical_id),
        )

    # Fresh registration un-archives the device (it is alive and reporting).
    unarchive_device(db, canonical_id)
    db.commit()

    # Sync the WebSocket owner cache with the ACTUAL owner after the write.
    # COALESCE keeps an existing owner on re-register, so re-read the row to
    # avoid flipping the cache to the registering user when ownership didn't
    # change (which would leak another user's broadcasts to the wrong client).
    final_owner = db.execute("SELECT owner_id FROM devices WHERE id=?", (canonical_id,)).fetchone()
    update_device_owner(canonical_id, final_owner["owner_id"] if final_owner else None)

    tokens = create_device_tokens(canonical_id)
    log_audit("device_registered", actor=canonical_id, details=reg.model)

    return {
        **tokens,
        "device_id": canonical_id,
        "has_device_key": device_key_hash is not None,
        "owner_id": final_owner["owner_id"] if final_owner else None,
        "server_time": now,
    }


def _enforce_device_limit(db, user_id: str):
    """Raise 403 when the user already owns their plan's device allowance.

    The allowance comes from the account's tier (free=1, personal=3,
    guardian=10, enterprise/admin=unlimited) — see plan_device_limit().
    """
    tier_row = db.execute("SELECT tier FROM users WHERE id=?", (user_id,)).fetchone()
    tier = tier_row["tier"] if tier_row else "free"
    limit = plan_device_limit(tier)
    count = db.execute("SELECT COUNT(*) as cnt FROM devices WHERE owner_id=?", (user_id,)).fetchone()["cnt"]
    if count >= limit:
        raise HTTPException(
            status_code=403,
            detail=f"Device limit reached ({count}/{limit}) — upgrade your plan to protect more devices",
        )


@router.post("/api/device/claim")
async def claim_device(
    req: DeviceClaimRequest,
    db: sqlite3.Connection = Depends(get_db),
    user_id: str = Depends(get_current_user),
    x_device_key: Optional[str] = Header(None),
):
    """Link an existing device to the authenticated user's account.

    The device is identified by its per-device secret key (x-device-key header)
    or, failing that, by an explicit device_id in the body. The user is
    authenticated with a user bearer token. Once linked, the device shows up
    in the user's dashboard and is scoped to their account.
    """
    if user_id == "api_key_user":
        raise HTTPException(status_code=401, detail="User authentication required")

    # A stale token from a permanently deleted account must not claim devices
    # (that would re-create a ghost link — same bug class as register).
    if not _user_exists(db, user_id):
        raise HTTPException(status_code=401, detail="Account no longer exists")

    device = None
    if x_device_key:
        key_hash = hash_device_key(x_device_key)
        device = db.execute("SELECT id, owner_id FROM devices WHERE device_key_hash=?", (key_hash,)).fetchone()
    if device is None and req.device_id:
        device = db.execute("SELECT id, owner_id FROM devices WHERE id=?", (req.device_id,)).fetchone()
    if device is None:
        raise HTTPException(status_code=404, detail="Device not found")

    existing_owner = device["owner_id"]
    # Only block cross-account claims when the existing owner is a REAL account.
    # A device whose owner account was permanently deleted (orphaned ownership,
    # e.g. after a DB restore) is claimable by anyone with the device key/id.
    if existing_owner and _user_exists(db, existing_owner) and existing_owner != user_id:
        raise HTTPException(status_code=403, detail="Device already linked to another account")

    # Enforce per-user device limit before linking — skip when the device is
    # already owned by this user so re-claims stay idempotent (same as the
    # register path, which skips the limit for same-owner re-registrations).
    if existing_owner != user_id:
        _enforce_device_limit(db, user_id)

    db.execute("UPDATE devices SET owner_id=? WHERE id=?", (user_id, device["id"]))
    db.commit()
    update_device_owner(device["id"], user_id)
    log_audit("device_claimed", actor=user_id, details=f"Device: {device['id']}")

    return {"status": "ok", "device_id": device["id"], "owner_id": user_id}


# ─── Location Reports ────────────────────────────────────────────────────────


def location_row_exists(conn: sqlite3.Connection, device_id: str, report: TelemetryPing) -> bool:
    """True when this exact ping (device + seq + device-clock timestamp) was
    already persisted.

    At-most-once guard: OkHttp's default retryOnConnectionFailure re-sends the
    SAME body when the connection dies after the server processed it (seen
    live: a captive-portal reconnect inserted every ping twice — the server
    got the request, the response was lost, the client re-POSTed the identical
    body ~45s later). A normal (non-unique) index keeps this lookup cheap;
    the check itself is the constraint, so existing dirty rows don't block
    the migration.
    """
    if not report.ping_sequence:
        return False
    row = conn.execute(
        "SELECT 1 FROM locations WHERE device_id=? AND ping_sequence=? AND device_timestamp=? LIMIT 1",
        (device_id, report.ping_sequence, report.device_timestamp),
    ).fetchone()
    return row is not None


def _persist_location(
    conn: sqlite3.Connection,
    *,
    device_id: str,
    report: TelemetryPing,
    score: int,
    threat_level: str,
    anomalies: list,
    now: str,
    ts: str,
) -> None:
    """Insert one location row + refresh the device row.

    Shared by the synchronous path (runs on the request connection) and the
    batched path (runs on the write queue's dedicated connection). Keeping
    the SQL in one place guarantees the two paths can never drift.

    At-most-once: a retried/duplicate ping (same device + ping_sequence +
    device_timestamp) is skipped — the device row's last_seen still refreshes
    below, but no second row is inserted.
    """
    if location_row_exists(conn, device_id, report):
        return
    # At-rest encryption (v1.5): when MT_ENCRYPTION_KEY is configured, the
    # coordinates are AES-256-GCM encrypted with the per-device HKDF key — the
    # row stores 0.0 placeholders + ciphertext in location_data. Sentinel and
    # the WebSocket feed already run on the in-memory `report` payload, so
    # encrypting at the DB boundary never affects theft detection.
    lat, lng, loc_enc, loc_data = encrypt_location_for_store(report.lat, report.lng, device_id)
    conn.execute(
        """INSERT INTO locations (device_id, lat, lng, altitude, accuracy_horizontal,
           accuracy_vertical, confidence_level, speed, bearing, activity_type,
           step_count, provider, gps_satellite_count, wifi_bssids, cell_tower_ids,
           ble_devices_nearby, battery_percent, is_charging, network_type,
           signal_strength_dbm, is_location_enabled, is_airplane_mode,
           sim_changed, sim_serial_hash, sentinel_score, threat_level, anomalies,
           device_timestamp, server_timestamp, was_queued, queued_at,
           queue_position, ping_sequence, location_encrypted, location_data)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            device_id,
            lat,
            lng,
            report.altitude,
            report.accuracy_horizontal,
            report.accuracy_vertical,
            report.confidence_level,
            report.speed,
            report.bearing,
            report.activity_type,
            report.step_count,
            report.provider,
            report.gps_satellite_count,
            json.dumps(report.wifi_bssids or []),
            json.dumps(report.cell_tower_ids or []),
            report.ble_devices_nearby,
            report.battery_percent,
            report.is_charging,
            report.network_type,
            report.signal_strength_dbm,
            report.is_location_enabled,
            report.is_airplane_mode,
            report.sim_changed,
            report.sim_serial_hash,
            score,
            threat_level,
            json.dumps(anomalies or []),
            ts,
            now,
            report.was_queued,
            report.queued_at,
            report.queue_position,
            report.ping_sequence,
            loc_enc,
            loc_data,
        ),
    )

    # COALESCE: an old app build that doesn't send capture_armed (None) must
    # not wipe the stored state — the column keeps its last known value.
    conn.execute(
        "UPDATE devices SET last_seen=?, sentinel_score=?, capture_armed=COALESCE(?, capture_armed) WHERE id=?",
        (now, score, report.capture_armed, device_id),
    )


def _queue_auto_action(db, device_id: str, command: str):
    """Queue one geofence auto-action command (priority 1, poll delivery),
    deduplicated against an identical already-pending row.

    The exit transition fires exactly once (last_inside is persisted below),
    but the device may keep pinging from outside the zone — without this
    guard each ping would queue another capture/siren until the first one
    expired.
    """
    pending = db.execute(
        "SELECT 1 FROM commands WHERE device_id=? AND command=? AND status='pending' LIMIT 1",
        (device_id, command),
    ).fetchone()
    if pending:
        return
    now = datetime.now(timezone.utc).isoformat()
    # Mirror issue_command's expiry policy: the alarm is sensitive (5 min),
    # the evidence captures get the standard 30-minute window.
    expires = (datetime.now(timezone.utc) + timedelta(minutes=5 if command == "alarm" else 30)).isoformat()
    db.execute(
        "INSERT INTO commands (device_id, command, params, status, priority, issued_at, expires_at, delivery_channel) "
        "VALUES (?, ?, '', 'pending', 1, ?, ?, 'poll')",
        (device_id, command, now, expires),
    )


def _alert_recent(device_id: str, alert_type: str, minutes: int = 10) -> bool:
    """True when an alert of the given type was already logged for this device
    in the last `minutes` minutes. Shared by the location and heartbeat paths
    so one incident (including queued/offline replays of the same flag) = one
    always-deliver alert.

    Reads through the CURRENT database module (resolved at call time) rather
    than the request connection: alert_engine.send_all resolves
    `from database import get_db_context` at call time too, so under
    full-suite test eviction it writes rows to a DIFFERENT module than the
    one the request's `db` came from. Reading the same module send_all
    writes keeps the dedup truthful (same convention as test_alert_settings
    seeding the current module). Single-process production has one module,
    so the two are identical there.

    sent_at is written by SQLite as CURRENT_TIMESTAMP (UTC, 'YYYY-MM-DD
    HH:MM:SS') — comparing against datetime('now', '-N minutes') is
    apples-to-apples UTC.
    """
    import database as _current_db

    with _current_db.get_db_context() as conn:
        recent = conn.execute(
            "SELECT 1 FROM alerts WHERE device_id=? AND alert_type=? "
            "AND datetime(sent_at) > datetime('now', ?) LIMIT 1",
            (device_id, alert_type, f"-{minutes} minutes"),
        ).fetchone()
    return recent is not None


def _sim_changed_alert_recent(device_id: str) -> bool:
    """True when a sim_changed alert was already logged for this device in the
    last 10 minutes. Shared by the location and heartbeat paths so one incident
    (including queued/offline replays of the same flag) = one always-deliver
    alert."""
    return _alert_recent(device_id, "sim_changed")


def _failed_unlock_capture_recent(db, device_id: str, minutes: int = 5) -> bool:
    """True when a failed-unlock capture pair was already queued for this
    device within the last `minutes` minutes.

    The on-device EVIDENCE window is ~5 minutes, so one pair per window
    keeps evidence flowing while a locked device keeps pinging — without the
    continuous re-queue flood. G1-9 (found in the real-theft field test): a
    photo/audio pair re-queued every ~15s while the count stayed above the
    threshold, and the resulting request burst from one mobile IP got the
    device's network path to the server blocked (last_seen frozen, uploads
    failing with HTTP -1 / read timeouts) — exactly the moment evidence
    MUST upload.

    Reads through the REQUEST connection (`db`) — the same connection that
    inserts the commands — so the check is exact and has none of the
    module-eviction ambiguity of a separately-resolved connection.
    """
    recent = db.execute(
        "SELECT 1 FROM commands WHERE device_id=? "
        "AND command IN ('capture_photo_front', 'capture_audio') "
        "AND datetime(issued_at) > datetime('now', ?) LIMIT 1",
        (device_id, f"-{minutes} minutes"),
    ).fetchone()
    return recent is not None


def _queue_failed_unlock_reaction(db, device_id: str) -> None:
    """Queue the "theftie" evidence pair (front photo + ambient audio) for a
    device whose failed-unlock count crossed the threshold.

    Reuses the geofence auto-action machinery: priority-1 poll commands,
    deduplicated against identical already-pending rows so a device that
    keeps pinging from a locked screen never piles up repeats — and bounded
    to ONE pair per EVIDENCE window (G1-9) so the reaction can never flood
    the device's network path (see _failed_unlock_capture_recent).
    """
    if _failed_unlock_capture_recent(db, device_id):
        return
    _queue_auto_action(db, device_id, "capture_photo_front")
    _queue_auto_action(db, device_id, "capture_audio")


@router.post("/api/device/location")
async def post_location(
    report: TelemetryPing,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Receive telemetry ping from device."""
    if report.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_location_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")

    now = datetime.now(timezone.utc).isoformat()

    # Validate GPS coordinates before processing - reject obviously invalid
    # fixes (ocean, Antarctica, garbage values) but log them for diagnostics.
    loc_valid, loc_reason, loc_warning = validate_location_report(
        report.lat, report.lng, report.accuracy_horizontal, report.provider
    )
    if not loc_valid:
        logger.warning(
            "Rejecting invalid location report",
            extra={"extra_data": {"device_id": device_id, "reason": loc_reason}},
        )
        log_audit("invalid_location", actor=device_id, details=loc_reason)
        # Still return success to avoid tipping off the device, but don't
        # persist the garbage coordinates.
        commands = db.execute(
            "SELECT id, command, params, priority FROM commands"
            " WHERE device_id=? AND status='pending'"
            " ORDER BY priority",
            (device_id,),
        ).fetchall()
        return {"status": "ok", "commands_pending": len(commands), "server_time": now}

    is_valid, reason = sentinel.validate_report(report, None)
    if not is_valid:
        log_audit("invalid_location_report", actor=device_id, details=reason)
    ts = report.device_timestamp or now

    history = db.execute(
        "SELECT * FROM locations WHERE device_id=? ORDER BY server_timestamp DESC LIMIT 10",
        (device_id,),
    ).fetchall()

    # Sentinel's haversine/geofence math runs on REAL coordinates — decrypt
    # any encrypted history rows before compute_score (encrypted rows carry
    # 0.0 placeholders in lat/lng; passing those through would poison the
    # movement/velocity signals).
    history_dicts = []
    for h in history:
        hd = dict(h)
        hd["lat"], hd["lng"] = decrypt_location_row(hd)
        history_dicts.append(hd)
    score, threat_level, anomalies = sentinel.compute_score(report, history_dicts)

    # Batched path (opt-in, MT_WRITE_BATCH_MS>0): defer the INSERT + device
    # UPDATE to this worker's write queue so the request NEVER contends for
    # SQLite's single-writer lock (measured: sync commits cap the whole server
    # at ~370 req/s with 3s p50 latency — batching collapses N commits into one
    # and makes the request path a read-only WAL reader). The device row's
    # last_seen lands within one flush window (~250ms); the dashboard is not
    # delayed because the WebSocket broadcast below carries the fresh fix+score
    # immediately. If the queue is enabled but not yet started, enqueue_write
    # returns False and we fall back to the synchronous path — a write is
    # never silently dropped.
    if write_queue_enabled() and enqueue_write(
        partial(
            _persist_location,
            device_id=device_id,
            report=report,
            score=score,
            threat_level=threat_level,
            anomalies=anomalies,
            now=now,
            ts=ts,
        )
    ):
        # unarchive stays on the request connection: it is a no-op unless the
        # device was archived, and when it writes it must be durable now.
        unarchive_device(db, device_id)
        db.commit()
    else:
        _persist_location(
            db,
            device_id=device_id,
            report=report,
            score=score,
            threat_level=threat_level,
            anomalies=anomalies,
            now=now,
            ts=ts,
        )
        # Fresh telemetry un-archives a device that came back online.
        unarchive_device(db, device_id)
        db.commit()

    if score >= settings.THEFT_SCORE_THRESHOLD:
        sentinel.auto_activate_theft_mode(device_id, score)
        await alert_engine.send_all(
            device_id,
            "theft_detected",
            {"location": f"{report.lat},{report.lng}", "time": now, "score": score},
        )

    # SIM change fires its OWN always-deliver alert the instant it is
    # reported — the owner must know a different SIM was inserted even when
    # the theft score has not accumulated to the confirmation threshold
    # (sim_changed alone scores 35/80). The device flags the change exactly
    # once; the 10-minute dedup also absorbs queued/offline replays so one
    # incident = one alert (tradeoff: two GENUINE swaps within 10 minutes are
    # coalesced — the owner is still alerted to the first, and the SIM
    # fingerprint is re-baselined on-device).
    if report.sim_changed and not _sim_changed_alert_recent(device_id):
        await alert_engine.send_all(
            device_id,
            "sim_changed",
            {"location": f"{report.lat},{report.lng}", "time": now},
        )

    # Failed-unlock "theftie" reaction (COMPETITOR_AUDIT P1 #4): repeated
    # failed unlock attempts strongly suggest a stranger in possession, and
    # the owner must know NOW while the device is still with the thief.
    # Sentinel already scored the signal above (+20, if it crossed the
    # threshold); here we queue the evidence pair (front photo + ambient
    # audio — the same commands geofence exits use) and fire an
    # always-deliver alert. Deduped: _queue_failed_unlock_reaction skips
    # identical already-pending commands, and the 10-minute alert window
    # absorbs queued/offline replays so one incident = one alert (same
    # tradeoff as sim_changed).
    if report.failed_unlock_count is not None and report.failed_unlock_count >= settings.FAILED_UNLOCK_THRESHOLD:
        _queue_failed_unlock_reaction(db, device_id)
        # Commit BEFORE send_all (same nested-write hazard documented on the
        # geofence path below: send_all opens its own connection).
        db.commit()
        if not _alert_recent(device_id, "failed_unlock_attempts"):
            await alert_engine.send_all(
                device_id,
                "failed_unlock_attempts",
                {
                    "attempts": report.failed_unlock_count,
                    "location": f"{report.lat},{report.lng}",
                    "time": now,
                },
            )

    geofences = db.execute("SELECT * FROM geofences WHERE device_id=? AND active=1", (device_id,)).fetchall()

    if geofences:
        triggered = sentinel.check_geofences(report, [dict(g) for g in geofences])
        # Collect the exits that need an alert so the alert fires AFTER the
        # transaction below is committed — send_all() opens its OWN connection
        # and writes alert rows; calling it while this request connection still
        # holds uncommitted writes makes it block on our lock and raise
        # "database is locked" after busy_timeout (same hazard the heartbeat
        # path documents — see post_heartbeat's "Commit BEFORE any nested
        # writes" note).
        exits_to_alert = []
        for event in triggered:
            # Persist the per-zone inside/outside state so the SAME transition
            # is never re-reported on later pings. This write is what makes
            # check_geofences' was_inside truthful: without it every ping saw
            # was_inside=False and 'exited' events (and the exit alert) could
            # never fire — dead code in production (v1.5 fix).
            db.execute(
                "UPDATE geofences SET last_inside=? WHERE id=?",
                (1 if event["event"] == "entered" else 0, event["geofence_id"]),
            )
            if event["event"] != "exited":
                continue
            # Geofence exit alert — fires for SAFE-ZONE exits (the product
            # meaning: "your device left the safe zone"). The template says
            # 'safe zone' but the old condition checked `not is_safe_zone`, so
            # exiting HOME never alerted while exiting a restricted zone did —
            # inverted vs. the product intent (v1.5 fix).
            if event["is_safe_zone"]:
                exits_to_alert.append(event)
            # Per-zone auto-actions (owner-set policy): react on the device
            # itself, regardless of safe/restricted classification (the owner
            # chose this reaction for THIS zone). 'capture' = front-camera
            # photo + ambient audio (the theft-mode evidence pair); 'siren' =
            # max-volume alarm. Deduped against already-pending identical
            # commands so one exit never piles up repeats.
            action = event.get("auto_action")
            if action == "capture":
                _queue_auto_action(db, device_id, "capture_photo_front")
                _queue_auto_action(db, device_id, "capture_audio")
            elif action == "siren":
                _queue_auto_action(db, device_id, "alarm")
        db.commit()
        for event in exits_to_alert:
            await alert_engine.send_all(
                device_id,
                "geofence_exit",
                {
                    "zone_name": event["name"],
                    "location": f"{report.lat},{report.lng}",
                    "time": now,
                },
            )

    # Accuracy is a core part of a tracking UI ("±12m" vs "±500m" changes
    # what the operator trusts). The dashboard's live map/panel reads
    # accuracy_horizontal — this broadcast used to omit it (and
    # provider/bearing/confidence), so the real-time feed always rendered
    # "±?m" even though the device reported the fused Kalman accuracy on
    # every ping.
    await broadcast_to_dashboards(
        {
            "type": "location",
            "data": {
                "device_id": device_id,
                "lat": report.lat,
                "lng": report.lng,
                "speed": report.speed,
                "battery": report.battery_percent,
                "sentinel_score": score,
                "threat_level": threat_level,
                "timestamp": now,
                "accuracy_horizontal": report.accuracy_horizontal,
                "provider": report.provider,
                "bearing": report.bearing,
                "confidence_level": report.confidence_level,
            },
        }
    )

    commands = db.execute(
        "SELECT id, command, params, priority FROM commands WHERE device_id=? AND status='pending' ORDER BY priority",
        (device_id,),
    ).fetchall()

    return {
        "status": "ok",
        "commands_pending": len(commands),
        "server_time": now,
    }


@router.post("/api/device/location/simple")
async def post_location_simple(
    report: LocationReport,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Simplified location report for basic tracking."""
    if report.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    now = datetime.now(timezone.utc).isoformat()
    ts = report.timestamp or now

    # Regression (shipped once): the INSERT referenced an `accuracy` column
    # that doesn't exist in the locations schema (it's accuracy_horizontal),
    # so every call 500'd with "no such column: accuracy". The request model
    # keeps its `accuracy` field for API compatibility; only the column name
    # is mapped to the real one.
    lat, lng, loc_enc, loc_data = encrypt_location_for_store(report.lat, report.lng, device_id)
    db.execute(
        (
            "INSERT INTO locations (device_id, lat, lng, accuracy_horizontal, provider, "
            "device_timestamp, server_timestamp, location_encrypted, location_data) "
            "VALUES (?,?,?,?,?,?,?,?,?)"
        ),
        (
            device_id,
            lat,
            lng,
            report.accuracy,
            report.provider,
            ts,
            now,
            loc_enc,
            loc_data,
        ),
    )
    db.execute("UPDATE devices SET last_seen=? WHERE id=?", (now, device_id))
    db.commit()

    return {"status": "ok", "server_time": now}


# ─── Media Uploads ───────────────────────────────────────────────────────────


@router.post("/api/device/media")
async def post_media(
    report: MediaReport,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Upload media (photo/audio) from device."""
    if report.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_media_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Media upload rate limit exceeded")

    now = datetime.now(timezone.utc).isoformat()
    ts = report.timestamp or now

    # Media storage refactor (v1.4): evidence bytes go to DISK via
    # media_store.py — validated (per-type size caps + magic bytes) BEFORE
    # any decode, so an oversized or bogus payload is rejected with 413/415
    # instead of spiking memory or bloating the SQLite file. The row keeps
    # metadata + the file's SHA-256; legacy base64 stays empty for new rows.
    from media_store import MediaValidationError, save_media

    try:
        stored = save_media(device_id, report.type, report.data_b64)
    except MediaValidationError as e:
        raise HTTPException(status_code=e.status_code, detail=str(e))

    data = base64.b64decode(report.data_b64)
    sha256_hash = hashlib.sha256(data).hexdigest()

    case = db.execute(
        "SELECT id FROM evidence_cases WHERE device_id=? AND status='active' ORDER BY created_at DESC LIMIT 1",
        (device_id,),
    ).fetchone()

    case_id = case["id"] if case else None

    db.execute(
        """INSERT INTO media (device_id, type, data_b64, lat, lng, timestamp,
           evidence_case_id, sha256_hash, file_path, file_size)
           VALUES (?, ?, '', ?, ?, ?, ?, ?, ?, ?)""",
        (
            device_id,
            report.type,
            report.lat,
            report.lng,
            ts,
            case_id,
            sha256_hash,
            stored["file_path"],
            stored["file_size"],
        ),
    )
    db.commit()

    media_id = db.execute("SELECT last_insert_rowid()").fetchone()[0]

    if case_id:
        evidence_builder.add_media_to_case(case_id, report.type, report.data_b64)

    await broadcast_to_dashboards(
        {
            "type": "media",
            "data": {
                "device_id": device_id,
                "media_id": media_id,
                "type": report.type,
                "timestamp": ts,
            },
        }
    )

    return {
        "status": "ok",
        "media_id": media_id,
        "evidence_case_id": case_id,
    }


# ─── Commands (Device Polling) ───────────────────────────────────────────────


@router.get("/api/device/commands/{device_id}")
async def get_device_commands(
    device_id: str,
    db: sqlite3.Connection = Depends(get_db),
    token_device_id: str = Depends(get_current_device_or_key),
):
    """Poll for pending commands."""
    if device_id != token_device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_command_poll_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Command poll rate limit exceeded")

    rows = db.execute(
        """SELECT id, command, params, priority
           FROM commands
           WHERE device_id=? AND status='pending'
           AND (delivery_channel IS NULL OR delivery_channel != 'sms')
           AND (expires_at IS NULL OR datetime(expires_at) > datetime('now'))
           ORDER BY priority ASC""",
        (device_id,),
    ).fetchall()

    return {"commands": [dict(r) for r in rows]}


@router.post("/api/device/commands/{command_id}/ack")
async def ack_command(
    command_id: int,
    ack: CommandAck,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Acknowledge command execution.

    A failed ack may carry a failure_reason (e.g. "Microphone muted — set
    Microphone to Allow all the time") so the dashboard explains WHY a
    capture failed instead of showing a bare red FAILED.
    """
    now = datetime.now(timezone.utc).isoformat()

    # A failure_reason is only meaningful for a FAILED ack — persist it for
    # those, and always clear it on an 'executed' ack (a stale reason from an
    # earlier failed attempt must never linger on a row that succeeded, or the
    # dashboard would show a contradiction).
    reason = ack.failure_reason if ack.status == "failed" else None

    db.execute(
        "UPDATE commands SET status=?, executed_at=?, failure_reason=? WHERE id=? AND device_id=?",
        (ack.status, now, reason, command_id, device_id),
    )
    db.commit()

    await broadcast_to_dashboards(
        {
            "type": "command_ack",
            "data": {
                "command_id": command_id,
                "device_id": device_id,
                "status": ack.status,
                "failure_reason": ack.failure_reason,
            },
        }
    )

    return {"status": "ok"}


# ─── Heartbeat ───────────────────────────────────────────────────────────────


@router.post("/api/device/heartbeat")
async def post_heartbeat(
    hb: HeartbeatPacket,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Receive heartbeat from device."""
    if hb.device_id != device_id:
        raise HTTPException(status_code=403, detail="Device ID mismatch")

    if not check_heartbeat_rate_limit(device_id):
        raise HTTPException(status_code=429, detail="Heartbeat rate limit exceeded")

    now = datetime.now(timezone.utc).isoformat()

    db.execute(
        """INSERT INTO heartbeats (device_id, timestamp, battery_percent, is_charging,
           network_type, device_admin_active, sim_hash, app_version, pending_evidence_count)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            device_id,
            now,
            hb.battery_percent,
            hb.is_charging,
            hb.network_type,
            hb.device_admin_active,
            hb.sim_hash,
            hb.app_version,
            hb.pending_evidence_count,
        ),
    )

    # COALESCE keeps the last known armed state when an old app build omits
    # the field (None) — a fresh report never wipes it to NULL.
    db.execute(
        "UPDATE devices SET last_seen=?, app_version=?, capture_armed=COALESCE(?, capture_armed) WHERE id=?",
        (now, hb.app_version, hb.capture_armed, device_id),
    )

    # Fresh heartbeat un-archives a device that came back online.
    unarchive_device(db, device_id)

    # ── Commit BEFORE any nested writes ──────────────────────────────────────
    # auto_activate_theft_mode() and log_audit() open their OWN sqlite
    # connection. Calling them while this request's write transaction is still
    # open makes the nested writer block on our uncommitted writes and raise
    # "database is locked" after busy_timeout — the resulting 500 rolls back
    # the heartbeat's last_seen update, so the dashboard freezes the device's
    # "last seen" at its previous time even though the phone is alive.
    db.commit()

    # Device admin being disabled is a strong theft signal (weight 40 in
    # sentinel.THEFT_SIGNALS), but it must NOT auto-activate stolen mode from a
    # bare heartbeat: escalation is reserved for the location path's
    # confirmation-gated score (>= THEFT_SCORE_THRESHOLD). Persist the elevated
    # score so the dashboard reflects the signal; the location path still owns
    # escalation to stolen.
    if hb.device_admin_active is False:
        db.execute(
            "UPDATE devices SET sentinel_score = MAX(sentinel_score, 40) WHERE id=?",
            (device_id,),
        )
        db.commit()

    # Location/airplane state over the heartbeat too (G1-10): a device with
    # location services OFF pings 0,0 — the location path rejects the
    # coordinates BEFORE Sentinel can score them — so location_disabled (+20)
    # and airplane_mode (+15) never registered (and the app didn't report
    # them at all). Same belt-and-braces pattern as admin_disabled above:
    # carry the state on the heartbeat and raise the persisted score so the
    # dashboard reflects the signal. SUMs the applicable weights (matching
    # compute_score's additive behavior); MAX keeps the location path's
    # fresher score authoritative.
    hb_signal_score = 0
    if hb.is_location_enabled is False:
        hb_signal_score += sentinel.THEFT_SIGNALS["location_disabled"]["weight"]
    if hb.is_airplane_mode:
        hb_signal_score += sentinel.THEFT_SIGNALS["airplane_mode_on"]["weight"]
    if hb_signal_score:
        db.execute(
            "UPDATE devices SET sentinel_score = MAX(sentinel_score, ?) WHERE id=?",
            (hb_signal_score, device_id),
        )
        db.commit()

    # SIM change over the heartbeat (belt-and-braces for devices whose
    # location stream is quiet — e.g. location permission revoked): same
    # always-deliver alert, same 10-minute dedup as the location path.
    if hb.sim_changed and not _sim_changed_alert_recent(device_id):
        last = db.execute(
            "SELECT lat, lng FROM locations WHERE device_id=? " "ORDER BY server_timestamp DESC LIMIT 1",
            (device_id,),
        ).fetchone()
        loc = f"{last['lat']},{last['lng']}" if last else "unknown"
        await alert_engine.send_all(device_id, "sim_changed", {"location": loc, "time": now})

    # Failed-unlock "theftie" over the heartbeat too (same belt-and-braces
    # as sim_changed: the 60s heartbeat runs even when the location stream
    # is quiet, so a locked screen is still reported). Same reaction and same
    # 10-minute dedup as the location path.
    if hb.failed_unlock_count is not None and hb.failed_unlock_count >= settings.FAILED_UNLOCK_THRESHOLD:
        _queue_failed_unlock_reaction(db, device_id)
        db.commit()
        if not _alert_recent(device_id, "failed_unlock_attempts"):
            last = db.execute(
                "SELECT lat, lng FROM locations WHERE device_id=? " "ORDER BY server_timestamp DESC LIMIT 1",
                (device_id,),
            ).fetchone()
            loc = f"{last['lat']},{last['lng']}" if last else "unknown"
            await alert_engine.send_all(
                device_id,
                "failed_unlock_attempts",
                {"attempts": hb.failed_unlock_count, "location": loc, "time": now},
            )

    device = db.execute("SELECT operating_mode FROM devices WHERE id=?", (device_id,)).fetchone()

    return {
        "status": "ok",
        "operating_mode": device["operating_mode"] if device else "normal",
        "server_time": now,
    }


# ─── Token Refresh ───────────────────────────────────────────────────────────


@router.post("/api/device/refresh")
async def refresh_token(req: RefreshRequest):
    """Refresh JWT tokens."""
    return refresh_access_token(req.refresh_token)


# ─── Offline Queue ───────────────────────────────────────────────────────────


@router.post("/api/device/offline-queue")
async def upload_offline_queue(
    queue: OfflineQueueUpload,
    db: sqlite3.Connection = Depends(get_db),
    device_id: str = Depends(get_current_device_or_key),
):
    """Batch upload of queued telemetry pings."""
    processed = 0
    last_armed = None

    for ping in queue.pings:
        if ping.device_id != device_id:
            continue
        # At-most-once (same contract as the live path): a ping that already
        # landed via a previous flush or a live retry is skipped, never
        # double-inserted.
        if location_row_exists(db, device_id, ping):
            continue

        now = datetime.now(timezone.utc).isoformat()
        ts = ping.device_timestamp or now

        history = db.execute(
            "SELECT * FROM locations WHERE device_id=? ORDER BY server_timestamp DESC LIMIT 10",
            (device_id,),
        ).fetchall()
        # Same decryption-before-Sentinel contract as the live path (above):
        # encrypted history rows must expose real coordinates to the scorer.
        history_dicts = []
        for h in history:
            hd = dict(h)
            hd["lat"], hd["lng"] = decrypt_location_row(hd)
            history_dicts.append(hd)
        score, threat_level, anomalies = sentinel.compute_score(ping, history_dicts)

        lat, lng, loc_enc, loc_data = encrypt_location_for_store(ping.lat, ping.lng, device_id)
        db.execute(
            """INSERT INTO locations (device_id, lat, lng, altitude, accuracy_horizontal,
               confidence_level, speed, bearing, activity_type, provider,
               battery_percent, is_charging, network_type, sentinel_score,
               threat_level, anomalies, device_timestamp, server_timestamp, was_queued,
               queued_at, queue_position, ping_sequence, location_encrypted, location_data)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                device_id,
                lat,
                lng,
                ping.altitude,
                ping.accuracy_horizontal,
                ping.confidence_level,
                ping.speed,
                ping.bearing,
                ping.activity_type,
                ping.provider,
                ping.battery_percent,
                ping.is_charging,
                ping.network_type,
                score,
                threat_level,
                json.dumps(anomalies or []),
                ts,
                now,
                True,
                ping.queued_at,
                ping.queue_position,
                ping.ping_sequence,
                loc_enc,
                loc_data,
            ),
        )
        last_armed = ping.capture_armed
        processed += 1

    # Same COALESCE keep-last-state semantics as the live telemetry path: a
    # queued ping's capture_armed is persisted when present, and a None (old
    # build) never wipes a previously reported state.
    db.execute(
        "UPDATE devices SET last_seen=?, capture_armed=COALESCE(?, capture_armed) WHERE id=?",
        (datetime.now(timezone.utc).isoformat(), last_armed, device_id),
    )
    unarchive_device(db, device_id)
    db.commit()

    return {"status": "ok", "processed": processed}


# ─── FCM Token Registration ─────────────────────────────────────────────────


class FCMTokenRequest(BaseModel):
    fcm_token: str
    device_id: str = ""
    platform: Optional[str] = "android"


@router.post("/api/device/fcm-token")
async def register_fcm_token(
    req: FCMTokenRequest,
    db: sqlite3.Connection = Depends(get_db),
    resolved_device_id: str = Depends(get_current_device_or_key),
):
    """Register an FCM push notification token for a device.

    Security (F-06): this endpoint must never create device rows. The old
    code inserted a placeholder device (fingerprint='fcm_*') for ANY
    device_id, so anyone could pollute the devices table — and the shared
    device key (public, embedded in every APK) let anyone do it with an
    arbitrary id. The device must ALREADY be registered: real devices
    authenticate with their per-device key/JWT (resolved_device_id is then
    their real id), and the fcm_tokens.device_id FK enforces existence.
    """
    now = datetime.now(timezone.utc).isoformat()

    device_id = resolved_device_id

    # The shared device key (embedded in every APK — public) has NO principal,
    # so it must not be able to attach a push token to an arbitrary device:
    # with the old fallback, anyone with the key could register their own FCM
    # token under a victim's EXISTING device_id and receive the victim's theft
    # alerts (push hijacking). The only non-device id still accepted is the
    # fixed 'broadcast' relay constant, which the alert engine uses to fan out
    # to tokens registered without a device (kept for backward compat).
    if device_id == "api_key_user" or not device_id:
        requested = req.device_id.strip() if req.device_id else ""
        if requested != "broadcast":
            raise HTTPException(status_code=401, detail="Device authorization required")
        device_id = "broadcast"

    # A device that isn't registered yet must reject the token registration
    # (the app registers the device before sending its FCM token). The
    # legacy 'broadcast' relay is the one allowed non-device id — it is a
    # fixed constant, not attacker-controlled.
    if device_id != "broadcast":
        existing = db.execute("SELECT id FROM devices WHERE id=?", (device_id,)).fetchone()
        if not existing:
            raise HTTPException(status_code=401, detail="Device not registered")

    db.execute(
        """INSERT INTO fcm_tokens (device_id, fcm_token, platform, updated_at)
           VALUES (?, ?, ?, ?)
           ON CONFLICT(device_id, fcm_token) DO UPDATE SET updated_at=?""",
        (device_id, req.fcm_token, req.platform, now, now),
    )
    db.commit()

    logger.info(
        "FCM token registered",
        extra={"extra_data": {"device_id": device_id, "platform": req.platform}},
    )

    return {"status": "ok", "message": "FCM token registered", "device_id": device_id}
