package com.magneetar.app

import android.app.Activity
import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import android.widget.Toast
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

/**
 * Offline Device Network §4.1 — pair this device with another of the
 * OWNER's devices (same account). One-time code bootstrap over the
 * internet; after that the two devices can talk fully offline (siren/lock/
 * lost_mode/ping via P2pOfflineService).
 *
 * Two paths:
 *   - GENERATE: this device initiates — the owner types the 8-hex code
 *     into the other device. This screen then polls the server and stores
 *     the shared secret when the other device confirms.
 *   - ENTER: the owner types a code generated by the other device; this
 *     device confirms and stores the shared secret immediately.
 *
 * Covert-style minimal programmatic UI (matches HomeActivity's style —
 * no XML layout, dark background).
 */
class PairingActivity : Activity() {

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main)
    private lateinit var statusText: TextView
    private lateinit var codeInput: EditText
    private lateinit var pairList: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        buildUi()
        refresh()
        scope.launch { syncFromServer() }
    }

    private fun buildUi() {
        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(48, 64, 48, 48)
            setBackgroundColor(Color.rgb(18, 18, 18))
        }

        root.addView(TextView(this).apply {
            text = "Pair a device"
            setTextColor(Color.WHITE)
            textSize = 20f
        })

        root.addView(TextView(this).apply {
            text = "Pair two of YOUR devices to control them offline (no internet needed)."
            setTextColor(Color.GRAY)
            textSize = 13f
            setPadding(0, 12, 0, 24)
        })

        // ── Generate path ────────────────────────────────────────────────
        root.addView(Button(this).apply {
            text = "GENERATE CODE"
            setOnClickListener { generateCode() }
        })

        root.addView(TextView(this).apply {
            text = "This device starts the pairing. Show the code to your other device."
            setTextColor(Color.GRAY)
            textSize = 12f
            setPadding(0, 8, 0, 24)
        })

        // ── Enter path ───────────────────────────────────────────────────
        codeInput = EditText(this).apply {
            hint = "Enter 8-char code from your other device"
            inputType = android.text.InputType.TYPE_CLASS_TEXT
            setTextColor(Color.WHITE)
            setHintTextColor(Color.GRAY)
        }
        root.addView(codeInput)

        root.addView(Button(this).apply {
            text = "ENTER CODE"
            setOnClickListener { enterCode() }
        })

        statusText = TextView(this).apply {
            setTextColor(Color.WHITE)
            textSize = 14f
            setPadding(0, 16, 0, 16)
        }
        root.addView(statusText)

        // ── Paired devices ───────────────────────────────────────────────
        root.addView(TextView(this).apply {
            text = "Paired devices"
            setTextColor(Color.WHITE)
            textSize = 16f
            setPadding(0, 24, 0, 8)
        })

        pairList = TextView(this).apply {
            setTextColor(Color.GRAY)
            textSize = 13f
        }
        root.addView(pairList)

        root.addView(Button(this).apply {
            text = "OPEN OFFLINE NETWORK"
            setOnClickListener {
                P2pOfflineService.start(this@PairingActivity)
                Toast.makeText(this@PairingActivity, "Offline network active", Toast.LENGTH_SHORT).show()
            }
        })

        val scroll = ScrollView(this).apply {
            addView(root)
        }
        setContentView(scroll)
    }

    private fun generateCode() {
        statusText.text = "Generating pairing code..."
        scope.launch {
            val deviceId = deviceId()
            val result = PairingApi.initiate(this@PairingActivity, deviceId)
            if (result == null || result.pairCode.isEmpty()) {
                statusText.text = "Failed to generate a code. Check sign-in and try again."
                return@launch
            }
            statusText.text = "Pairing code: ${result.pairCode}\nEnter it on your other device (valid 15 min)."
            // Poll until the other device confirms, then store the secret.
            pollUntilSecret(deviceId, result.pairId)
        }
    }

    private fun enterCode() {
        val code = codeInput.text.toString().trim()
        if (code.length != 8) {
            Toast.makeText(this, "Code must be 8 characters", Toast.LENGTH_SHORT).show()
            return
        }
        statusText.text = "Confirming pairing..."
        scope.launch {
            val deviceId = deviceId()
            val result = PairingApi.confirm(this@PairingActivity, deviceId, code)
            if (result == null || result.pairSecret.isEmpty()) {
                statusText.text = "Code rejected. It may be expired or already used — generate a new one."
                return@launch
            }
            PairVault.save(
                this@PairingActivity,
                PairVault.Pairing(
                    pairId = result.pairId,
                    deviceA = result.deviceA,
                    deviceB = result.deviceB,
                    secret = result.pairSecret.hexToBytes(),
                    createdAt = System.currentTimeMillis(),
                ),
            )
            statusText.text = "Paired with ${result.deviceB}\nOffline control is now available."
            refresh()
        }
    }

    private suspend fun pollUntilSecret(deviceId: String, pairId: String) {
        // The other device confirms with the code; this device then sees the
        // pairing in status and stores the shared secret. Poll for up to 15
        // minutes (the code TTL), pausing briefly between attempts.
        repeat(15 * 60) {
            kotlinx.coroutines.delay(1_000)
            val pairings = PairingApi.status(this@PairingActivity, deviceId)
            val mine = pairings.firstOrNull { it.pairId == pairId && it.pairSecret.isNotEmpty() }
            if (mine != null) {
                PairVault.save(
                    this@PairingActivity,
                    PairVault.Pairing(
                        pairId = mine.pairId,
                        deviceA = mine.deviceA,
                        deviceB = mine.deviceB,
                        secret = mine.pairSecret.hexToBytes(),
                        createdAt = System.currentTimeMillis(),
                    ),
                )
                statusText.text = "Paired with ${mine.deviceB}\nOffline control is now available."
                refresh()
                return
            }
        }
        statusText.text = "Timed out waiting for the other device. Generate a new code."
    }

    private suspend fun syncFromServer() {
        val deviceId = deviceId()
        PairingApi.syncToVault(this, deviceId)
        refresh()
    }

    private fun refresh() {
        val pairs = PairVault.list(this)
        pairList.text = if (pairs.isEmpty()) {
            "No paired devices yet."
        } else {
            pairs.joinToString("\n\n") { p ->
                val peer = if (p.deviceA == deviceId()) p.deviceB else p.deviceA
                "• $peer\n  pair ${p.pairId.take(12)}…  ${java.text.SimpleDateFormat("MMM d, HH:mm", java.util.Locale.getDefault()).format(java.util.Date(p.createdAt))}"
            }
        }
    }

    private fun deviceId(): String =
        getSharedPreferences("mt", android.content.Context.MODE_PRIVATE)
            .getString("device_id", "") ?: ""

    override fun onDestroy() {
        super.onDestroy()
        scope.cancel()
    }

    private fun String.hexToBytes(): ByteArray {
        if (length % 2 != 0) return ByteArray(0)
        return ByteArray(length / 2) { i -> substring(i * 2, i * 2 + 2).toInt(16).toByte() }
    }
}
