#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# MAGNEETAR — One-Line Server Installation
# Usage: curl -fsSL https://magneetar.me/install.sh | bash
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                                                            ║"
    echo "║   ███╗   ███╗ █████╗ ███████╗ ██████╗ ██╗   ██╗██╗███╗   ██╗  ║"
    echo "║   ████╗ ████║██╔══██╗██╔════╝██╔═══██╗██║   ██║██║████╗  ██║  ║"
    echo "║   ██╔████╔██║███████║███████╗██║   ██║██║   ██║██║██╔██╗ ██║  ║"
    echo "║   ██║╚██╔╝██║██╔══██║╚════██║██║   ██║╚██╗ ██╔╝██║██║╚██╗██║  ║"
    echo "║   ██║ ╚═╝ ██║██║  ██║███████║╚██████╔╝ ╚████╔╝ ██║██║ ╚████║  ║"
    echo "║   ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝  ╚═══╝  ║"
    echo "║                                                            ║"
    echo "║   Anti-Theft Tracking System — Server Installer            ║"
    echo "║   magneetar.me | @magneetarhq                             ║"
    echo "║                                                            ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# ─── Check Prerequisites ─────────────────────────────────────────────────────

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check OS
    if [[ "$OSTYPE" != "linux-gnu"* ]]; then
        log_error "This script is designed for Linux (Ubuntu 22.04+)"
        exit 1
    fi

    # Check if running as root or with sudo
    if [[ $EUID -ne 0 ]]; then
        log_warn "This script requires sudo. Please run with sudo or as root."
        exit 1
    fi

    # Check Python 3.10+
    if ! command -v python3 &> /dev/null; then
        log_info "Python 3 not found. Installing..."
        apt-get update -qq
        apt-get install -y -qq python3 python3-pip python3-venv
    fi

    PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    if [[ $(echo "$PYTHON_VERSION < 3.10" | bc -l) -eq 1 ]]; then
        log_error "Python 3.10+ required. Found: $PYTHON_VERSION"
        exit 1
    fi

    # Check Git
    if ! command -v git &> /dev/null; then
        log_info "Git not found. Installing..."
        apt-get install -y -qq git
    fi

    log_info "Prerequisites OK"
}

# ─── Install Magneetar ────────────────────────────────────────────────────────

install_magneetar() {
    INSTALL_DIR="/opt/magneetar"
    log_info "Installing Magneetar to $INSTALL_DIR..."

    # Clone or update repository
    if [[ -d "$INSTALL_DIR" ]]; then
        log_info "Updating existing installation..."
        cd "$INSTALL_DIR"
        git pull origin main
    else
        log_info "Cloning repository..."
        git clone https://github.com/magneetar/magneetar.git "$INSTALL_DIR"
        cd "$INSTALL_DIR"
    fi

    # Create virtual environment
    log_info "Creating Python virtual environment..."
    cd server
    python3 -m venv venv
    source venv/bin/activate

    # Install dependencies
    log_info "Installing Python dependencies..."
    pip install -q --upgrade pip
    pip install -q -r requirements.txt

    log_info "Magneetar installed to $INSTALL_DIR"
}

# ─── Generate Secrets ─────────────────────────────────────────────────────────

generate_secrets() {
    ENV_FILE="/opt/magneetar/.env"

    if [[ -f "$ENV_FILE" ]] && grep -q "MT_API_KEY=.\{32,\}" "$ENV_FILE"; then
        log_info "Existing .env file found with secrets. Skipping generation."
        return
    fi

    log_info "Generating secure secrets..."

    API_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(64))")
    ENCRYPTION_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")

    cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════════════════════════
# MAGNEETAR SERVER CONFIGURATION
# Generated by install.sh on $(date -Iseconds)
# ═══════════════════════════════════════════════════════════════════════════════

# Core Security
MT_API_KEY=${API_KEY}
MT_JWT_SECRET=${JWT_SECRET}
MT_ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Database
MT_DB_PATH=/opt/magneetar/server/magneetar.db

# Environment
MT_ENVIRONMENT=production
MT_HOST=0.0.0.0
MT_PORT=8000
MT_LOG_LEVEL=info

# Limits
MT_MAX_DEVICES=5
MT_RETENTION_DAYS=90

# Alert Services (configure for production)
# MT_SENDGRID_KEY=your-sendgrid-api-key
# MT_TERMII_KEY=your-termii-api-key
# MT_ALERT_EMAIL=admin@magneetar.me
# MT_ALERT_PHONE=+234XXXXXXXXXX
EOF

    chmod 600 "$ENV_FILE"
    log_info "Secrets generated and saved to $ENV_FILE"
    log_warn "IMPORTANT: Store these secrets securely!"
    log_warn "API Key: ${API_KEY:0:8}...${API_KEY: -8}"
}

# ─── Install Systemd Service ──────────────────────────────────────────────────

install_service() {
    log_info "Installing systemd service..."

    cat > /etc/systemd/system/magneetar.service << EOF
[Unit]
Description=Magneetar Anti-Theft Server
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/magneetar/server
EnvironmentFile=/opt/magneetar/.env
ExecStart=/opt/magneetar/server/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --log-level info
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/opt/magneetar/server
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable magneetar
    log_info "Systemd service installed"
}

# ─── Configure Firewall ──────────────────────────────────────────────────────

configure_firewall() {
    log_info "Configuring UFW firewall..."

    if command -v ufw &> /dev/null; then
        ufw allow 22/tcp comment "SSH"
        ufw allow 8000/tcp comment "Magneetar API"
        ufw --force enable
        log_info "Firewall configured"
    else
        log_warn "UFW not found. Please configure your firewall manually."
    fi
}

# ─── Start Services ───────────────────────────────────────────────────────────

start_services() {
    log_info "Starting Magneetar server..."
    systemctl start magneetar

    sleep 2
    if systemctl is-active --quiet magneetar; then
        log_info "Magneetar server is running!"
    else
        log_error "Failed to start Magneetar. Check: journalctl -u magneetar -f"
        exit 1
    fi
}

# ─── Print Summary ────────────────────────────────────────────────────────────

print_summary() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           MAGNEETAR INSTALLATION COMPLETE!                 ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    SERVER_IP=$(hostname -I | awk '{print $1}')
    API_KEY=$(grep MT_API_KEY /opt/magneetar/.env | cut -d= -f2)

    echo -e "  ${CYAN}Server URL:${NC}      http://${SERVER_IP}:8000"
    echo -e "  ${CYAN}Health Check:${NC}    http://${SERVER_IP}:8000/health"
    echo -e "  ${CYAN}Dashboard:${NC}       http://${SERVER_IP}:8000/dashboard"
    echo -e "  ${CYAN}API Key:${NC}         ${API_KEY:0:16}..."
    echo ""
    echo -e "  ${YELLOW}Management Commands:${NC}"
    echo -e "    Start:    systemctl start magneetar"
    echo -e "    Stop:     systemctl stop magneetar"
    echo -e "    Status:   systemctl status magneetar"
    echo -e "    Logs:     journalctl -u magneetar -f"
    echo -e "    Restart:  systemctl restart magneetar"
    echo ""
    echo -e "  ${YELLOW}Next Steps:${NC}"
    echo -e "    1. Configure alerts in /opt/magneetar/.env"
    echo -e "    2. Install the Android APK on your device"
    echo -e "    3. Open the dashboard and enter your API key"
    echo ""
    echo -e "  ${GREEN}TRACK · PROTECT · RECOVER${NC}"
    echo -e "  magneetar.me | @magneetarhq"
    echo ""
}

# ─── Main ─────────────────────────────────────────────────────────────────────

main() {
    print_banner
    check_prerequisites
    install_magneetar
    generate_secrets
    install_service
    configure_firewall
    start_services
    print_summary
}

main "$@"
